
self.app = {
	debug: true,
	cacheName: "whitespider-unblocker",
	cacheVersion: "1.2.0",
	cacheList: [
		"lib/socket.io.min.js",
		"lib/webalert.js",
		"res/ubuntu/ubuntu-condensed.ttf",
		"res/ubuntu/ubuntu-mono.ttf",
		"res/ubuntu/ubuntu.css",
		"res/ubuntu/ubuntu.ttf",
		"res/add.svg",
		"res/back.svg",
		"res/extension.svg",
		"res/facebook.svg",
		"res/forward.svg",
		"res/google.svg",
		"res/home.svg",
		"res/instagram.svg",
		"res/logo.svg",
		"res/logo2.svg",
		"res/logo64.png",
		"res/logo128.png",
		"res/logo256.png",
		"res/logo512.png",
		"res/more.svg",
		"res/refresh.svg",
		"res/tiktok.svg",
		"res/winxperror.wav",
		"res/y8.svg",
		"res/youtube.svg",
		"uv/uv.bundle.js",
		"uv/uv.client.js",
		"uv/uv.config.js",
		"uv/uv.handler.js",
		"uv/uv.sw.js",
		"404.xht",
		"app.js",
		"b64.js",
		"favicon.ico",
		"favicon0.ico",
		"index.xht",
		"main.js",
		"manifest.json",
		"robots.txt",
		"standard.css",
		"sw.js",
		"uv.xht"
	],
	headers: {
		"Cross-Origin-Embedder-Policy": "require-corp",
		"Cross-Origin-Opener-Policy": "same-origin",
		"X-Content-Type-Options": "nosniff"
	}
};
